name: fail2ban

services:
  fail2ban:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "UTC"
        F2B_LOG_TARGET: "STDOUT"
        F2B_LOG_LEVEL: "INFO"
        F2B_DB_PURGE_AGE: "1d"
        IPTABLES_MODE: "auto"
        F2B_NO_DEB_DEFAULTS: ""
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    read_only: true
    volumes:
      - ./data:/data
      - ./data/run:/var/run/fail2ban
      - ./data/lib:/var/lib/fail2ban
      - /var/log:/var/log:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    restart: always
