name: cleanup

on:
  schedule:
    - cron: "0 2 1 * *"

  workflow_dispatch:
    inputs:
      keep:
        description: "Number of tags to keep"
        required: false
        type: number
        default: 5

  workflow_call:
    inputs:
      keep:
        description: "Number of tags to keep"
        required: false
        type: number
        default: 5
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      KEEP: ${{ inputs.keep }}

    steps:
      - name: Delete old GHCR versions
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        continue-on-error: true
        with:
          package-name: "fail2ban"
          package-type: "container"
          # Hardcoding 17 for now
          min-versions-to-keep: 17

      - name: Delete old Docker Hub versions
        run: |
          set -e

          echo "Login Docker Hub"

          TOKEN=$(curl -s \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\":\"${{ secrets.DOCKERHUB_USERNAME }}\",\"password\":\"${{ secrets.DOCKERHUB_TOKEN }}\"}" \
            https://hub.docker.com/v2/users/login/ \
            | jq -r .token)

          if [ -z "$TOKEN" ]; then
            echo "Docker Hub login failed"
            exit 1
          fi

          echo "Fetching tags..."

          TAGS=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/tags?page_size=100" \
            | jq -r '(.results // []) | sort_by(.last_updated) | reverse | .[].name')

          if [ -z "$TAGS" ]; then
            echo "Didn't find any tags. Skipping..."
            exit 0
          fi

          echo "Current tags:"
          echo "$TAGS"

          TO_DELETE=$(echo "$TAGS" | tail -n +$(($KEEP+1)))

          for TAG in $TO_DELETE
          do
            if [ "$TAG" = "latest" ] || [ "$TAG" = "edge" ]; then
              continue
            fi

            echo "Deleting $TAG"

            curl -s \
              -X DELETE \
              -H "Authorization: Bearer $TOKEN" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/tags/$TAG/"

          done
