name: cleanup

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:
    inputs:
      keep:
        description: "Number of tags to keep"
        required: false
        default: "5"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old GHCR versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: "fail2ban"
          package-type: "container"
          min-versions-to-keep: ${{ github.event.inputs.keep }}

      - name: Delete old Docker Hub versions
        shell: bash
        run: |
          set -e

          echo "Login Docker Hub"

          TOKEN=$(curl -s \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\":\"${{ secrets.DOCKERHUB_USERNAME }}\",\"password\":\"${{ secrets.DOCKERHUB_TOKEN }}\"}" \
            https://hub.docker.com/v2/users/login/ \
            | jq -r .token)

          if [ "$TOKEN" = "null" ]; then
            echo "Docker Hub login failed"
            exit 1
          fi

          echo "Fetch tags"

          TAGS=$(curl -s \
            -H "Authorization: JWT ${TOKEN}" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/tags?page_size=100" \
            | jq -r '.results | sort_by(.last_updated) | reverse | .[].name')

          if [ "$TAGS" = "null" ]; then
            echo "Didn't find any tags"
            exit 1
          fi

          echo "Current tags:"
          echo "$TAGS"

          DELETE=$(echo "$TAGS" | tail -n +$((${{ github.event.inputs.keep }}+1)))

          for TAG in $DELETE
          do
            if [ "$TAG" = "latest" ] || [ "$TAG" = "edge" ]; then
              continue
            fi

            echo "Deleting ${TAG}"

            curl -s \
              -X DELETE \
              -H "Authorization: JWT ${TOKEN}" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/tags/${TAG}/"

          done

          echo "Get untagged manifests"

          curl -s \
            -H "Authorization: JWT ${TOKEN}" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/images/" \
          | jq -r '
              .results[]
              | select(.tag == null)
              | .digest
            ' \
          > digests.txt


          while read digest
          do
            [ -z "$digest" ] && continue

            echo "Deleting digest ${digest}"

            curl -s \
              -X DELETE \
              -H "Authorization: JWT ${TOKEN}" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/fail2ban/images/${digest}/"

          done < digests.txt
